use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn projects_base() -> PathBuf {
    dirs::home_dir()
        .expect("No home directory")
        .join(".ikrs-workspace")
        .join("projects")
}

#[tauri::command]
pub async fn claude_preflight() -> Result<bool, String> {
    let output = Command::new("which")
        .arg("claude")
        .output()
        .map_err(|e| format!("Failed to check claude: {e}"))?;
    Ok(output.status.success())
}

#[tauri::command]
pub async fn scaffold_claude_project(
    client_slug: String,
    client_name: String,
    account_email: String,
    vault_path: String,
    timezone: String,
    description: String,
) -> Result<String, String> {
    let project_path = projects_base().join(&client_slug);
    fs::create_dir_all(project_path.join(".claude/commands"))
        .map_err(|e| e.to_string())?;

    let claude_md = format!(
        "# {client_name} — Engagement Context\n\n\
        ## Client\n\
        - **Name:** {client_name}\n\
        - **Consultant:** (auto-generated by IKAROS Workspace)\n\n\
        ## Connected Services\n\
        - Gmail: {account_email}\n\
        - Calendar: {account_email}\n\
        - Drive: {account_email}\n\
        - Obsidian vault: {vault_path}\n\n\
        ## Engagement\n\
        - **Scope:** {description}\n\
        - **Timezone:** {timezone}\n\n\
        ## Working Conventions\n\
        - Task list is in tasks.md — keep it updated\n\
        - Meeting notes go in the vault at 01-meetings/\n\
        - Deliverables go in 03-deliverables/\n"
    );
    fs::write(project_path.join("CLAUDE.md"), claude_md)
        .map_err(|e| e.to_string())?;

    let settings = serde_json::json!({
        "mcpServers": {}
    });
    let settings_path = project_path.join(".claude/settings.json");
    fs::write(&settings_path, serde_json::to_string_pretty(&settings).unwrap())
        .map_err(|e| e.to_string())?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&settings_path, fs::Permissions::from_mode(0o600))
            .map_err(|e| e.to_string())?;
    }

    Ok(project_path.to_string_lossy().to_string())
}

#[tauri::command]
pub async fn launch_claude(
    project_path: String,
    terminal: String,
) -> Result<u32, String> {
    let child = if cfg!(target_os = "macos") {
        Command::new("open")
            .args(["-a", &terminal, "--args", "claude", "--cwd", &project_path])
            .spawn()
    } else {
        Command::new("x-terminal-emulator")
            .args(["-e", &format!("cd {} && claude", project_path)])
            .spawn()
    };

    let child = child.map_err(|e| format!("Failed to launch Claude: {e}"))?;
    Ok(child.id())
}
